# Generated by Django 3.0.6 on 2020-05-25 09:53

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionSupport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
            ],
            options={
                'permissions': (('export_device', 'Can export device to GitLab'),
                                ('export_interface', 'Can export interface to GitLab')),
                'managed': False,
            },
        ),
    ]
